services:
  cman:
    image: rjchicago/cman:${VERSION:-latest}
    build: ./app
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
      - LEVEL=${LEVEL:-}
    volumes:
      - ./app/src:/app/src
      - ./app/levels:/app/levels
      - cman_data:/data

volumes:
  cman_data: