services:
  cman:
    image: rjchicago/cman:${VERSION:-latest}
    build: ./app
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
      - LEVEL=${LEVEL:-}
    volumes:
      - ./app/src:/app/src
      - ./app/levels:/app/levels
      - cman_data:/data

  cman-web:
    image: rjchicago/cman-web:${VERSION:-latest}
    build: ./web
    ports:
      - "8080:80"

  cman-web-dev:
    build:
      context: ./web
      target: build
    ports:
      - "5173:5173"
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
      - ./web/package.json:/app/package.json
      - ./web/tsconfig.json:/app/tsconfig.json
      - ./web/vite.config.ts:/app/vite.config.ts
    command: npm run dev
    environment:
      - VITE_HOST=0.0.0.0

volumes:
  cman_data: